### ISSUE TITLE
[Feature Request] Command: bonclay add

### ISSUE THREAD

**Issue by selfish** [talal/bonclay#2]
This should be rather simple, and allow avoiding manual modifications of the config file:
Command bonclay add will receive one or two arguments and add a file to the `spec` section.

Examples:
```
> bonclay add ./.dotfile .dotfile
```
Will move the file to the dotfiles folder, create the symlink, and update the `spec` with a new listing: `<fullpath>/.dotfile: .dotfile`

```
> bonclay add ./.somename
```
Will move the file to the dotfiles folder, create the symlink, and update the `spec` with a new listing: `<fullpath>/.dotfile: .somename`. Note that the filename is inferred.

Both will error on collision.

---
Sidenote, loving Bonclay! Thank you!

**Comment by talal** [comment]
Hi,

Glad to hear that you like Bonclay 😄 

I understand your use case and it is completely validated. However, I have to decline your feature request. The reason being that this use case is more suitable for a dotfiles manager. Bonclay is a very minimal utility that allows for simple backup/restore and file syncing.

It would be more appropriate to look for a proper utility for additional features and niceties.

For example: your use case is possible with this wonderful utility called [chezmoi](https://github.com/twpayne/chezmoi). You can do `chezmoi add ./some-file` and it does exactly what you described. Chezmoi is a dedicated tool for dotfile managment and it does that quite well, I would highly recommend looking into it.

**Comment by selfish** [comment]
Thanks for your response! 🙏
